---
- name: Set Docker repo compatible host's CPU architecture fact
  set_fact:
    arch_map:
      x86_64: amd64
      aarch64: arm64
    docker_host_arch: "{{ arch_map.get(ansible_architecture, ansible_architecture) }}"
