---
- name: Install docker role dependencies
  ansible.builtin.include_role:
    name: dependencies
    tasks_from: roles_deps/docker_dependencies.yml

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg
    mode: "0644"

- name: Dearmor GPG key
  ansible.builtin.command:
    cmd: gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg /tmp/docker.gpg
    creates: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Include docker_host_arch.yml task from common role
  ansible.builtin.include_role:
    name: common
    tasks_from: docker_host_arch.yml

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ docker_host_arch }} 
      signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] 
      https://download.docker.com/linux/{{ ansible_distribution | lower }} 
      {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker using apt-get
  ansible.builtin.apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - docker-buildx-plugin
    state: "present"
    force_apt_get: true
    update_cache: true

- name: Enable and start Docker service
  ansible.builtin.systemd_service:
    name: docker
    enabled: true
    state: started
