---
- name: Install python-dnf (dependency of 'ansible.builtin.dnf')
  block:
    - name: Install python3-dnf using shell
      shell: |
        if command -v dnf &>/dev/null; then
          dnf install -y python3-dnf
        elif command -v yum &>/dev/null; then
          yum install -y python3-dnf
        else
          echo "Neither dnf nor yum found. Cannot install python3-dnf."
          exit 1
        fi
      args:
        executable: /bin/bash
      register: install_result
      changed_when: "'Nothing to do.' not in install_result.stdout"

    - name: Check python3-dnf installation
      shell: rpm -q python3-dnf
      register: check_result
      changed_when: false
      failed_when: check_result.rc != 0

    - name: Show installation result
      debug:
        var: check_result.stdout_lines
