---
- name: Fetch Marzban JWT
  ansible.builtin.uri:
    url: "{{ marzban_subscription_subdomain }}.{{ marzban_domain }}/api/admin/token"
    method: POST
    headers:
      Accept: "application/json"
      Content-Type: "application/x-www-form-urlencoded"
    body:
      grant_type: ""
      username: "{{ marzban_username }}"
      password: "{{ marzban_password }}"
      scope: ""
      client_id: ""
      client_secret: ""
    body_format: form-urlencoded
    return_content: true
  register: api_response
